version: '2.1'
services:
  PostgreSQL:
    restart: always
    build: 
      context: .
    image: silverbulleters/ya-docker-postgresql-1c:latest
    # tmpfs:
    #   - /var/lib/postgresql/temptblspc
    ports:
      - "5432:5432"
    networks: 
      net:
        ipv4_address: 172.19.0.2
    #hostname: "docker.psql.local"
    environment:
      - USETMPFS_FOR_TMP=true
      - DEBUG=true
      - PG_PASSWORD=somepass
      - DB_USER=onecuser
      - DB_PASS=anotherpass
      - DB_NAME=powa,mamonsu
      - POWA_DATABASE=powa
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
      - REPLICATION_SSLMODE=
      - PG_TUNE_BY_MAMONSU=true
      - PG_MAX_CONNECTION=130
      - PG_TIMEZONE=Europe/Moscow
    volumes:
      - pg-data-master:/var/lib/postgresql/9.6/main
      - pg-temptbl-master:/var/lib/postgresql/temptblspc
      - pg-v81cdata-master:/var/lib/postgresql/v81c_data
      - pg-v81cindex-master:/var/lib/postgresql/v81c_index
      - pg-log-master:/var/log/postgresql

  PgAdminDBA:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
          - PostgreSQL
    ports: 
      - 8880:80
    networks:
      - net
    environment:
      - PGADMIN_DEFAULT_EMAIL=team@silverbulleters.org
      - PGADMIN_DEFAULT_PASSWORD=somepass
    #  - PGADMIN_ENABLE_TLS=
    #  - PGADMIN_SERVER_NAME=
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
    links: 
      - PostgreSQL:master
 #     - PostgreSQLSlave:slave

 
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
 
volumes:
   pg-data-master:
   pg-temptbl-master:
   pg-v81cdata-master:
   pg-v81cindex-master:
   pg-log-master:

   pgadmin-data:
   logstash-data:
   